### ISSUE TITLE
Context is not updated when state changes

### ISSUE THREAD

**Issue by ste93cry** [DomainGroupOSS/react-media-query-hoc#7]
I'm using React 16 with a component wrapped inside the `withMedia` HOC. Media queries works fine, refreshing the whole page at different resolutions I see that the state/context of the `MediaQueryProvider` component is correctly updated. However, resizing the window updates the state but not the context, so any child component won't see the new media queries values and won't trigger any layout change.

**Comment by jooj123** [comment]
Hi @ste93cry 

I cannot reproduce what you are seeing (although im not using React 16 yet)

Context is being updated from state changes here:
https://github.com/DomainGroupOSS/react-media-query-hoc/blob/b9901fdbb5aee27b0b2743ed3f8c95c3db3ee62b/src/media-query-provider.js#L22

And the different media query events are setup on mount here:
https://github.com/DomainGroupOSS/react-media-query-hoc/blob/b9901fdbb5aee27b0b2743ed3f8c95c3db3ee62b/src/media-query-provider.js#L30

Screen resizing works well across the domain code base (`react-media-query-hoc` is used extensively)

Can you provide an example of how you are using `react-media-query-hoc` ? 
Is this React 16 only ?
