### ISSUE TITLE
Prevent MediaQueryProvider from printing any additional div

### ISSUE THREAD

**Issue by ste93cry** [DomainGroupOSS/react-media-query-hoc#8]
As the `MediaQueryProvider` component should be used at the root-level of the application as stated in the docs, it makes no sense that it adds an additional element to the HTML structure. In my case, using a layout based on flexboxes that `div` that gets printed is a problem. Maybe you could use  `Children.only` like Apollo Client does to make this component "transparent"?

**Comment by jooj123** [comment]
Good point - no need for the extra div

Using `React.Children.only` sounds good, I can update this once I get a spare few mins - otherwise feel free to throw up a PR

**Comment by ste93cry** [comment]
I would like to point out that this change would introduce a BC break because `React.Children.only` throws if there is more than 1 child element, while instead it would have worked

**Comment by jooj123** [comment]
I think the ideal solution is to use React fragments: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Maybe best to wait for react 16 to be mainstream before this is put in - so this lib still works on React 15

**Comment by gricard** [comment]
FYI, my PR fixes this: https://github.com/DomainGroupOSS/react-media-query-hoc/pull/12

It does not fix the problem with React 15, though. It just adds support for Fragments.

**Comment by gricard** [comment]
Fixed in 0.5.0
